# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
